# Site settings
title: Страница vl.maksime на GitHub
description: Мой небольшой блог, работающий на GitHub Pages
author: Владимир Максименко
email: vl.maksime@gmail.com
github_username: vlmaksime

baseurl: ""
url: ""

google_analytics: UA-72862926-1
allowsearch: false

enableTags: false
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
