# Site settings
title: John Smith
description: My Personal Blog
author: John Smith
logo: /static/img/avatar.png
about: Freelance developer
email: ""
github_username: codeasashu

baseurl: ""
url: ""

allowsearch: true

# google_analytics: UA-72862926-1

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"

# Collections
collections:
  addons:
    output: true
    permalink: /releases/:path/

# Build settings
markdown: kramdown
plugins: [jekyll-paginate, jekyll-gist]
